### PR TITLE
feat: format all py files, new formatting script added

### PR DESCRIPTION
**Pull request by Kain-90**
## feat:
1. Support `make setup` to initialize the project
2. Support `make fmt` to format all py files in preparation for `pre-commit` later
3. Support for passing `--port(-p)` parameters to start services

## fix:
1. Dynamic support for embedding dimension values

### CODE REVIEW

**Comment by Kain-90** [comment]
@karanchellani Please take a look at this PR, thank you, and I'll be sure to follow up on this.

**Comment by karanchellani** [comment]
@Kain-90 please let us know the extension you have used in this case, would have it implemented in this project.

**Comment by Kain-90** [comment]
Thank you for your review. I used a combination of `isort`, `black`, and `blackdoc`. You can refer to this file for specific commands: `backend/Makefile`, it's also a good idea to check the corresponding configuration file `backend/.isort.cfg`

I originally planned to use Flake8, but I found that there were too many areas in the code that needed to be modified. I plan to decide whether to proceed after this PR.

**Comment by Kain-90** [comment]
@karanchellani hi, Any progress?

**Comment by karanchellani** [comment]
Hi @Kain-90 we have created separate branch for this, format using pre-commit, you can test it out.

**Pull request closed without merging**
