### PR TITLE
Add /extract API response to json file with nodes and relationships list same as diffbot response list 

### PR DESCRIPTION
**Pull request by aashipandya**
Added method 'update_response_to_jsonFile' in main.py

### CODE REVIEW

**Comment by jexp** [comment]
This should probably not be in main.py but a separate file, as it is the utility function meant to be used by the notebooks or?

**Comment by aashipandya** [comment]
Added update_response_to_jsonFile to api_response_to_json.py file.
Also added json response file with the latest records, @jexp Let me know if format is ok.

**Comment by jexp** [comment]
I think in general we should do one json file per pdf file and per model.
So they become easier to handle and compare side-by-side.

We would also need to use the same (or at least one with the same output format) utility function (output) for your experimental notebooks with the different models, so we have something comparabile.

**Comment by jexp** [comment]
I think we can close this one.

**Pull request closed without merging**
