### PR TITLE
fix: build frontend image

### PR DESCRIPTION
**Pull request by k8scat**
image

### CODE REVIEW

**Comment by k8scat** [comment]
@kartikpersistent why close the PR and create a new commit?

**Comment by k8scat** [comment]
https://github.com/neo4j-labs/llm-graph-builder/commit/b80a16439defde0f6dcf38aa4c9cb63d92f03a09

This commit has the same changes, is PR not welcomed in this project?

**Comment by kartikpersistent** [comment]
We generally not prefer to raise a pr directly to main first it can be raised to DEV then to stage and then to main because it was a critical issue I directly pushed hope you understand

**Comment by kartikpersistent** [comment]
If you find any issues in main/DEV feel free to raise to PR it is highly recommend

**Pull request closed without merging**
